[package]
name = "scrap"
description = "Screen capture made easy."
version = "0.0.1"
repository = "https://github.com/quadrupleslap/scrap"
license = "MIT"
authors = ["Ram <quadrupleslap@gmail.com>"]

[dependencies]
block = "0.1"
ioctl-gen = "0.1"
libc = "0.2"
